### ISSUE TITLE
Panic on slice bounds

### ISSUE THREAD

**Issue by ekristen** [progrium/gh-release#16]
I have an executable in the `release/` folder, the release seems to get created and a tag created too, but no files are actually uploaded against the release.

```
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
main.MimeType(0xc20800a030, 0x1, 0x1)
	/home/ubuntu/gh-release/gh-release.go:65 +0x35d
github.com/progrium/go-basher.(*Context).HandleFuncs(0xc20805e000, 0xc20800a000, 0x4, 0x4, 0x0)
	/home/ubuntu/.go_workspace/src/github.com/progrium/go-basher/basher.go:174 +0x2e5
github.com/progrium/go-basher.Application(0xc20803a420, 0xc20805af68, 0x1, 0x1, 0x193478, 0x1)
	/home/ubuntu/.go_workspace/src/github.com/progrium/go-basher/basher.go:56 +0x30e
main.main()
	/home/ubuntu/gh-release/gh-release.go:106 +0x21c

goroutine 2 [runnable]:
runtime.forcegchelper()
	/usr/local/go/src/runtime/proc.go:90
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 3 [runnable]:
runtime.bgsweep()
	/usr/local/go/src/runtime/mgc0.go:82
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 4 [runnable]:
runtime.runfinq()
	/usr/local/go/src/runtime/malloc.go:712
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1
```

**Comment by progrium** [comment]
Yeah I ran into this today as well. I'm assuming the API changed a bit.
